// Kepler — full content model. Domains → drivers → mechanisms as uniform peers, so every sibling
// renders at identical depth (Completeness Law §1.1a). Domain reuses the Engine type.

export type Row = (string | number)[];
export type Table = { cols: string[]; rows: Row[]; foot?: Row; negCols?: number[]; note?: string };
export type Code = { file: string; lines: string };
export type Mechanism = { id: string; title: string; body: string; cite?: string; table?: Table; code?: Code };
export type Driver = { id: string; title: string; body: string; cite?: string; table?: Table; mechanisms: Mechanism[] };
export type Engine = {
  id: string; n: string; name: string; term: string; today: string; target: string; swing: string;
  headline: string; lede: string; cite?: string; finding: string; findingBody: string; drivers: Driver[];
};

export const IDENTITY: Table = {
  cols: ['Domain', 'Owns / moves', 'Feeds →', '← Fed by'],
  rows: [
    ['D1 · Mobility', 'Density (D)', 'siting, routing, fraud, telemetry, all models', 'energy cost, models'],
    ['D2 · Energy', 'cost floor + Trust (T)', 'lowers D1/D3 cost; reliability → T', 'D1 location (siting)'],
    ['D3 · Logistics', 'Liquidity (L)', 'density, merchant data', 'D1 routing, D2 electrons, D4 cash-free, D6 matching'],
    ['D4 · Payments', 'Trust (T) + monetization', 'closes the loop cash-free; underwrites', 'D1/D3 behaviour, D6 fraud signals'],
    ['D5 · Devices', 'Data breadth (B)', 'proprietary sensor data → D6', 'rides in D1/D3, D4 on-device'],
    ['D6 · Data/AI', 'compounds all of M', 'serves models back to D1–D4', 'ingests all five'],
  ],
  note: 'M is a PRODUCT, not a sum: a conglomerate adds four mediocre terms and gets mediocrity; a flywheel multiplies them, so the weakest term caps the moat and each domain that lifts one term lifts the whole product. Target: blended contribution / interaction −$0.14 today → +$0.31 over ten years — driven by the moat lowering cost + raising trust across all six at once, not by any domain’s margin.',
};

export const SEQ: Table = {
  cols: ['Phase', 'Years', 'Build / deepen', 'Why here'],
  rows: [
    ['I', '1–2', 'D6 Data/AI platform FIRST', 'The hub must exist before any cross-feed can flow — the critical path.'],
    ['II', '2–4', 'D1 Mobility + D2 Energy', 'Mobility maxes Density (the term every later domain multiplies against); energy lowers cost + starts earning Trust.'],
    ['III', '4–6', 'D4 Payments', 'Needs D1/D3 behaviour to underwrite; arriving now, it monetises a moat that already exists.'],
    ['IV', '5–8', 'D3 Logistics + D5 Devices', 'Logistics thickens Liquidity on mobility’s routing + payments’ rails; devices deepen Breadth once D6 can exploit new streams.'],
    ['V', '8–10', 'Compound & defend', 'All feeds live; the moat compounds on its own; the work becomes defending + extending the flywheel.'],
  ],
  note: 'The load-bearing decision is Phase I: build the hub before the spokes. Sequence it last (the intuitive "prove the businesses, then connect them") and every domain hoards data that never compounds — the terms only add, and Kepler stays the mediocre conglomerate the market already prices.',
};

export const SCENARIOS = [
  { k: 'BASE · ≈50%', v: '+$0.31', body: 'Data-sharing tolerated, capital patient. Cross-feeds wire up on plan; the ~35% conglomerate discount inverts to a platform premium by year 8.' },
  { k: 'BULL · ≈20%', v: '+$0.48', body: 'Permissive regulation, cheap capital. The moat becomes genuinely uncatchable — but that dominance seeds regulatory backlash.' },
  { k: 'BEAR · ≈30%', v: '−$0.02', body: 'Data-sharing restricted, capital dear. Privacy law walls the domains off, cross-feeds become illegal, terms revert to adding, and the break-up case wins. The risk is regulatory, not operational.' },
];

export const CONTRIB = { today: -0.14, target: 0.31, weighted: 0.24 };

export const ENGINES: Engine[] = [
  {
    id: 'mobility', n: '01', name: 'Mobility', term: 'Density (D) — the feedstock', today: 'the D-engine', target: 'sequenced first (Phase II)', swing: '',
    headline: 'The density engine that feeds everything else.',
    lede: 'On its own numbers, Kepler mobility is a strong-but-not-singular robotaxi operation — utilization clears 70% in saturated zones, miles-per-intervention improved 11.6× in a year, the rider app is good, and the sensor stack still loses money per ride until solid-state lidar lands. A focused robotaxi specialist could match most of this line by line. None of it, standing alone, is uncatchable.',
    cite: 'S-118', finding: 'the densest interaction stream',
    findingBody: 'Mobility is the only domain that manufactures Interaction density (D) at scale, and D is the feedstock the entire flywheel runs on. The dwell heatmaps that site Energy chargers before demand exists (D2), the origin-destination tensor Logistics routes against (D3), the trajectory-plus-fingerprint stream that is Payments’ best fraud signal (D4), the raw telemetry that widens Breadth for Devices and every model (D5/D6) — none of these are mobility revenue, and all are mobility’s true output. Whoever owns the densest interaction stream owns the cheapest cost curve across all six businesses — and mobility is where that stream is born.',
    drivers: [
      { id: 'mo1', title: 'Driver 1 · The fleet & the density engine', cite: 'S-101',
        body: 'The fleet is not a transport asset; it is a mobile sensing grid that manufactures interaction density. Utilization in saturated zones clears 70%, and the value of a ride is double-counted: the fare, and the location-and-behaviour exhaust the other five domains consume.',
        mechanisms: [
          { id: 'mo1m1', title: 'Density as deliberate feedstock, not a by-product', cite: 'S-101', body: 'Kepler routes and prices the fleet to maximise coverage of the interaction manifold, not just fares — because every ride emits the dwell heatmaps, origin-destination tensor, and trajectory stream the rest of the flywheel is built on. A ride is worth what it earns plus what it teaches; run as a P&L, that second value is invisible, which is exactly why the market discounts it.' },
          { id: 'mo1m2', title: 'The location firehose that seeds five domains', cite: 'S-118', body: 'The proprietary location data is the input to Energy’s siting (chargers placed before demand exists, D1→D2), Logistics’ routing (the O-D tensor, D1→D3), Payments’ fraud model (trajectory + fingerprint, D1→D4), and every model in D6. No single-vertical robotaxi operator produces this because none touches the other five surfaces — the firehose is uncopyable, not merely large.' },
        ] },
      { id: 'mo2', title: 'Driver 2 · Safety & the trust it earns', cite: 'S-104',
        body: 'Safety is instrumented as an empirical frequency, not a brand claim — miles-per-intervention improved 11.6× in a year — and the trust it earns is fungible into the flywheel’s Trust term.',
        mechanisms: [
          { id: 'mo2m1', title: 'Miles-per-intervention as the safety scoreboard', cite: 'S-104', body: 'The 11.6× year-on-year improvement in miles-per-intervention is the atomic safety metric, tracked on a timeline the way credit tracks a loss curve. Each intervention is a labelled training example fed to D6, so safety compounds on the same data flywheel the rest of the platform runs on — the safest operator is the one with the densest, best-labelled intervention stream.' },
          { id: 'mo2m2', title: 'Safety trust is fungible across the platform', cite: 'S-120', body: 'A rider who has learned that a Kepler vehicle is safe is measurably more willing to trust a Kepler payment, charger, or device — trust earned in one surface is spent in another. This is the same coupling Energy exploits at the socket: physical-world reliability is a single reservoir the whole company draws on, which only a multi-surface operator can fill.' },
        ] },
      { id: 'mo3', title: 'Driver 3 · The rider experience', cite: 'S-110',
        body: 'The rider app is good on its own terms, but its strategic job is to keep density high: a better experience means more rides, which means more feedstock. Experience is a density lever disguised as a product.',
        mechanisms: [
          { id: 'mo3m1', title: 'Experience as a density multiplier', cite: 'S-110', body: 'Every point of retention or frequency the app buys is a point of interaction density added to the feedstock the other five domains consume — so app investment is under-priced if scored only against mobility revenue. The app is the intake valve of the density engine, not a standalone consumer product.' },
          { id: 'mo3m2', title: 'The cash-free ride closes the loop back to density', cite: 'S-404', body: 'Payments (D4) makes the ride cash-free, removing friction the driver and rider used to absorb — which raises completed-interaction count, which raises Density again. The experience improvement is manufactured by another domain’s rails: the flywheel showing up inside the rider app.' },
        ] },
      { id: 'mo4', title: 'Driver 4 · The vehicle & unit economics', cite: 'S-114',
        body: 'The sensor stack loses money per ride until solid-state lidar lands — the honest weak point of the domain read as a P&L. But the same stack is the physical instrument that manufactures the density and telemetry the flywheel monetises six times over.',
        mechanisms: [
          { id: 'mo4m1', title: 'The sensor stack: a cost per ride, an asset per platform', cite: 'S-114', body: 'Priced as a vehicle line, the lidar/compute stack is a margin drag until solid-state costs fall. Priced as a sensing grid, it is the cheapest way to instrument 42 cities continuously — the per-ride loss is the acquisition cost of a telemetry stream Devices and Data/AI pay nothing extra to reuse. The unit economics look bad in mobility’s column and good in the moat’s.' },
          { id: 'mo4m2', title: 'The teardown as the bridge into Devices (D5)', cite: 'S-121', body: 'The vehicle sensor manifold is the same modality set Devices ships in the KB-1 Beacon — kinematic, environmental, positional — so the fleet and the device line share a sensor grammar and a supply chain. Mobility proves the sensors at fleet scale; Devices extends the same manifold to fixed and portable form factors, widening Breadth (B) for the identical models.' },
        ] },
    ],
  },
  {
    id: 'energy', n: '02', name: 'Energy & Charging', term: 'cost floor + Trust (T)', today: 'utility-grade standalone', target: 'reliability engine', swing: '',
    headline: 'The cost floor and the reliability that earns trust.',
    lede: 'On its own books, Energy is the least attractive standalone business in the portfolio — capital-intensive, exposed to a commodity it cannot control, margin-thin even in its good branches (a probability-weighted +$0.036/kWh is a utility number, not a software one). A focused charge-point specialist would run a leaner balance sheet and trade at a cleaner multiple. That is why the sum-of-parts view marks it down.',
    cite: 'S-201', finding: 'sell the floor once, bank it six times',
    findingBody: 'Energy moves two moat terms — cost and Trust — for the whole flywheel. It sets a ~$0.082/kWh cost floor under Mobility and Logistics that widens exactly when the grid gets expensive, siting itself off D1’s location data so the asset is placed where the network will actually need it. And it manufactures trust at the socket — 99.2% uptime, a first-session success that drives 4.1× retention — that Payments then spends at the checkout, converting reliable chargers into activated wallets at 58% versus a 29% baseline. The charge is never the product; the cost floor and the trust ceiling are, and only Kepler gets to sell them once and bank them six times.',
    drivers: [
      { id: 'en1', title: 'Driver 1 · The charging network as an asset', cite: 'S-118',
        body: 'A charging estate is worth owning only if it is sited where the network will need it and integrated up the power stack — both of which Kepler can do because it reads Mobility’s demand before it materialises.',
        mechanisms: [
          { id: 'en1m1', title: 'Siting fed by Mobility’s location data (D1→D2)', cite: 'S-118', body: 'A standalone operator sites against public, laggy traffic counts every competitor sees simultaneously. Kepler sites against D1’s proprietary dwell heatmaps — placing chargers before demand exists, where the fleet already shows the network will need them. The first cross-feed made concrete: mobility data measurably lowers energy’s siting cost, an edge no charge-point specialist can buy.' },
          { id: 'en1m2', title: 'Vertical integration of the power economics', cite: 'S-203', body: 'Because aggregate load is forecastable from the fleet data behind siting, Kepler contracts power as an industrial buyer — long-dated PPAs, wholesale exposure, on-site storage — rather than a retail price-taker. A well-sited, dual-fed estate is worth owning up the stack; the same forecast that places the asset also finances its electrons cheaply.' },
        ] },
      { id: 'en2', title: 'Driver 2 · Load, demand & dispatch', cite: 'S-208',
        body: 'Demand is not flat, and the shape of the load curve is the whole game — two patterns dominate, and pricing plus dispatch reshape them into margin.',
        mechanisms: [
          { id: 'en2m1', title: 'Reading the load curve', cite: 'S-208', body: 'The estate’s load curve has two dominant patterns (fleet-charging troughs, public-demand peaks); reading them is the precondition for every energy-margin lever. The curve is legible only because the fleet’s own charging is a large, predictable share of it — a standalone operator sees a noisier, thinner signal.' },
          { id: 'en2m2', title: 'Dynamic pricing and dispatch optimisation', cite: 'S-209', body: 'Given the curve, one margin object does two coupled things: it prices demand to flatten peaks and dispatches charging (and stored energy) into the troughs. Both run off the same optimisation, and both are cheaper to run because the fleet’s flexible load is a controllable input, not just exogenous demand.' },
        ] },
      { id: 'en3', title: 'Driver 3 · Reliability & the trust it buys', cite: 'S-210',
        body: 'Trust in physical infrastructure is an empirical frequency, not a brand attribute — a user trusts the network to the exact degree it works when they arrive, so it is instrumented obsessively and the trust it earns is spent elsewhere.',
        mechanisms: [
          { id: 'en3m1', title: 'Uptime as the atomic unit of trust', cite: 'S-210', body: '99.2% uptime and a high first-session success rate are the atomic trust metrics — a user’s trust is exactly the frequency with which the charger works on arrival. First-session success drives 4.1× retention, so reliability is not a cost of doing business; it is the mechanism that manufactures the Trust term of the moat.' },
          { id: 'en3m2', title: 'Reliability feeds T that Payments (D4) relies on', cite: 'S-211', body: 'Trust earned at the socket is fungible: a user who has learned the Kepler charger always works converts to an activated Kepler wallet at 58% versus a 29% baseline. This is the coupling that justifies housing energy and payments under one roof — Energy manufactures trust cheaply at the plug, Payments spends it at the checkout.' },
        ] },
      { id: 'en4', title: 'Driver 4 · The energy-transition scenario', cite: 'S-214',
        body: 'The domain’s ten-year margin branches on forces Kepler does not control — the grid-price path and the renewables mix — but the first three drivers are the instruments that bias it toward the good branches.',
        mechanisms: [
          { id: 'en4m1', title: 'The scenario tree from grid price to margin', cite: 'S-214', body: 'A 10-year branching tree runs from grid-price path → renewables mix → net domain contribution margin, yielding a probability-weighted +$0.036/kWh. The tree is honest about the domain’s commodity exposure — this is a utility-grade distribution, presented as a range, not asserted as a forecast.' },
          { id: 'en4m2', title: 'Siting and dispatch as the hedge against the tree', cite: 'S-215', body: 'The tree is not merely awaited: data-led siting concentrates the estate where renewables and storage scale fastest, and dispatch shifts load into cheap-and-clean windows — biasing Kepler toward the tree’s upper branches. The same D1-fed instruments that place the asset also hedge the commodity risk that would sink a standalone operator.' },
        ] },
    ],
  },
  {
    id: 'logistics', n: '03', name: 'Logistics Marketplace', term: 'Liquidity (L)', today: 'contribution-neutral', target: '+€0.71/order in dense cores', swing: '',
    headline: 'Liquidity is the product.',
    lede: 'Logistics is 18% of revenue, +34% yoy, roughly contribution-neutral at +€0.04/order today. It owns network liquidity (L) — the probability that, in any cell of any of the 42 cities, a courier and an order match inside the window both sides accept. L is the most fragile moat term because it is not a stock but a flow defended every fifteen minutes: a city can have thousands of couriers and hungry merchants and still clear at 61% if they are in the wrong places, priced wrong, or matched slowly.',
    cite: 'S-301', finding: 'the compounding is the fill rate',
    findingBody: 'L is manufactured almost entirely out of the other five domains: routing from D1, cheap energy from D2, instant cash-free settlement and merchant credit from D4, and a matching engine that compounds on D6’s models faster than any competitor can fund past. The 11-point fill-rate gap over a well-funded standalone at equal pay is not a subsidy Kepler is buying — it is the flywheel showing up in one number. Densify into cells Mobility mapped, pay the core on Energy’s cost base, settle on Payments’ rails, match on Data/AI’s models, and L lifts from 0.38 toward 0.71 — contribution-neutral becomes +€0.71/order in dense cores. Here more than anywhere, the compounding is not a story; it is the fill rate.',
    drivers: [
      { id: 'lo1', title: 'Driver 1 · Two-sided liquidity', cite: 'S-303',
        body: 'Liquidity is refused as a single "orders" number because that number hides two independent conversion pipelines — supply and demand — each with its own funnel and its own retention truth.',
        mechanisms: [
          { id: 'lo1m1', title: 'The liquidity composite and the two-sided funnel', cite: 'S-303', body: 'L is instrumented as two conversion funnels (courier-side and merchant-side), and the shape of each side is diagnostic: the funnel leaks hard at the same cliff on both sides. Managing "orders" as one number hides which side is failing — the composite makes the two-sided dynamic legible so the right side gets the intervention.' },
          { id: 'lo1m2', title: 'Cohort retention as the liquidity truth serum', cite: 'S-305', body: 'Because a funnel is a snapshot, the business is governed on cohort-retention curves — the un-gameable record of whether each side stuck. The courier curve smiles (a professional core re-engages, 19% of couriers doing 68% of volume); the merchant curve flattens high. The shapes reveal that liquidity is a retention problem, not an acquisition one.' },
        ] },
      { id: 'lo2', title: 'Driver 2 · Courier supply — the sell side', cite: 'S-308',
        body: 'A courier decides to accept or decline in under four seconds, so the sell side is manufactured by making earnings legible in that window and by modelling the true cost of the marginal hour.',
        mechanisms: [
          { id: 'lo2m1', title: 'The job-offer surface: earnings legible in one screen', cite: 'S-308', body: 'Everything that determines whether L holds — guaranteed payout, honest ETA, surge multiplier, batching — must be legible in the four-second accept window. The offer surface is engineered so a courier can trust the number instantly; an opaque or dishonest offer raises declines, which is L failing to clear one match at a time.' },
          { id: 'lo2m2', title: 'Supply elasticity and the cost of the marginal hour', cite: 'S-309', body: 'A professional core (19% of couriers doing 68% of volume) is inelastic and cheap; the casual tail is elastic and expensive, summoned only when demand spikes past what the core can clear. Modelling marginal courier-hour cost by tier lets Kepler pay the core on Energy’s cost base and reserve expensive elastic supply for genuine surges — a cost discipline a standalone at equal pay cannot match.' },
        ] },
      { id: 'lo3', title: 'Driver 3 · The matching engine', cite: 'S-312',
        body: 'The engine converts two piles of supply and demand into cleared orders — and it is the surface where the flywheel compounds fastest, because every match and every decline is a labelled training example.',
        mechanisms: [
          { id: 'lo3m1', title: 'Batch-optimal assignment, not greedy nearest', cite: 'S-312', body: 'On a short dispatch tick the engine batches open orders and idle couriers into a bipartite assignment solved for a blend of ETA, batching gain, courier fairness, and predicted acceptance — not naive nearest-courier. Batch-optimal matching is what lets three drops share one trip, and it is only affordable because D6 serves the acceptance-probability model the objective depends on.', code: { file: 'match_tick.py', lines: '<span class="c"># batch open orders × idle couriers → bipartite assignment (not greedy nearest)</span>\n<span class="k">def</span> <span class="f">assign</span>(orders, couriers):\n    cost = [[<span class="f">blend</span>(\n        eta(o, c),\n        <span class="pu">-</span>batching_gain(o, c),      <span class="c"># shared trips lower cost</span>\n        fairness(c),\n        <span class="pu">-</span>p_accept(o, c))          <span class="c"># D6-served acceptance model</span>\n      <span class="k">for</span> c <span class="k">in</span> couriers] <span class="k">for</span> o <span class="k">in</span> orders]\n    <span class="k">return</span> <span class="f">min_cost_matching</span>(cost)   <span class="c"># Hungarian over the tick’s batch</span>' } },
          { id: 'lo3m2', title: 'The engine as the compounding surface', cite: 'S-313', body: 'Every completed and every declined offer is a labelled example fed straight back to D6: match quality this quarter trains the acceptance model that raises fill next quarter. The matcher compounds on the platform’s models faster than any competitor can fund its way past — the 11-point fill-rate edge at equal pay is this loop, not a subsidy.' },
        ] },
      { id: 'lo4', title: 'Driver 4 · Merchant demand & density — the geometry', cite: 'S-316',
        body: 'The buy side is a geometry problem: below a critical order density the engine cannot stack drops, and surge is the fast lever that holds equilibrium when demand outruns supply.',
        mechanisms: [
          { id: 'lo4m1', title: 'Density as the batching multiplier', cite: 'S-316', body: 'Below a critical order density each order consumes a whole courier trip; above it, three drops share one trip and effective supply triples with no extra courier. Kepler manages cities toward that threshold by densifying into the exact cells Mobility already mapped — so the geometry the matcher exploits is manufactured by D1’s density, not bought with couriers.' },
          { id: 'lo4m2', title: 'Surge as the equilibrium regulator', cite: 'S-317', body: 'When demand spikes past supply, price is the only fast lever: surge pulls the elastic casual tail online (Driver 2) and secondarily rations demand, holding the supply–demand equilibrium that keeps L clearing. The equilibrium chart is the control surface, and surge is calibrated against the tiered marginal-cost model rather than maximised.' },
        ] },
    ],
  },
  {
    id: 'payments', n: '04', name: 'Payments & Fintech', term: 'Trust (T) + monetization', today: '+58% yoy, contribution positive', target: 'the flywheel’s closing device', swing: '',
    headline: 'Trust is the product, monetization is the by-product.',
    lede: 'Payments is the fastest-growing domain (+58% yoy), now earns most of its gross profit from durable, un-capped layers, and its per-interaction contribution has already turned positive. Interchange is legally near-zero across half of Kepler’s TPV, so the standalone "payments company" framing is not just incomplete — it is impossible in these markets. On a monoline basis Kepler Payments would trail a focused regional PSP on rate and a focused lender on scale.',
    cite: 'S-401', finding: 'how the moat gets paid',
    findingBody: 'None of the durable margin exists without the other five domains. The credit engine underwrites on D1 mobility regularity and D3 courier reliability; the fraud engine defends on D6 signals built from D1 telemetry and D5 fingerprints; the rails close the loop by making D1 and D3 cash-free, buying density and liquidity that never show up on Payments’ own P&L. Payments is the term-owner for Trust — the one term every other domain multiplies against in M = D×B×L×T — and the only domain that converts a high M into cash the balance sheet can see. Run as a sixth P&L it is capped at a vanishing interchange; sequenced as the flywheel’s closing device it becomes the mechanism by which the moat, finally, gets paid.',
    drivers: [
      { id: 'pa1', title: 'Driver 1 · The payments rails', cite: 'S-404',
        body: 'The rails are the substrate that makes every other domain cash-free — one ledger, orchestrated across 14 countries’ local rails, closing the loop on mobility and logistics.',
        mechanisms: [
          { id: 'pa1m1', title: 'A single unified ledger as the system of record', cite: 'S-402', body: 'Kepler runs one double-entry ledger that every domain posts into — a ride (D1), a charge (D2), a courier payout (D3), a device instalment (D5) — all as entries against the same account graph. The single ledger is what makes the cross-domain join possible: one user’s mobility, energy, delivery, and device flows are legible together, which is the raw material of both underwriting and monetization evidence.' },
          { id: 'pa1m2', title: 'PSP orchestration and local-rail routing', cite: 'S-403', body: 'No single scheme covers 14 countries economically, so Kepler orchestrates across card schemes, local instant-payment rails (UPI in India, PIX in Brazil, PayNow in Singapore) and bank-transfer/RTP networks, routing each transaction to the cheapest compliant path. Orchestration is a cost lever and a coverage lever — it is what lets the rails be cheap enough to make mobility and logistics cash-free at all.' },
          { id: 'pa1m3', title: 'Cash-free closure of D1 and D3', cite: 'S-404', body: 'Once the rails are unified and cheap, Kepler makes mobility and logistics cash-free — no driver handling notes, no courier reconciling coins. This is the first cross-domain coupling that pays back invisibly: removing cash friction raises completed-interaction count (Density) and clearing speed (Liquidity), buying D1 and D3 outcomes that never appear on the Payments P&L.' },
        ] },
      { id: 'pa2', title: 'Driver 2 · Credit & underwriting', cite: 'S-405',
        body: 'Payments lends on data no bank can see — platform behaviour exogenous to any credit bureau — and recycles the products back into the flywheel, while disciplining the correlated risk that behaviour-based underwriting carries.',
        mechanisms: [
          { id: 'pa2m1', title: 'Behavioural underwriting off D1 and D3 exhaust', cite: 'S-405', body: 'Kepler scores creditworthiness from behaviour a bureau cannot observe: a D3 courier with 18 months of on-time deliveries and stable D1 commuting patterns is a better risk than a thin-file applicant with an identical bureau score. The signal is proprietary and causal, not correlational — it is the exhaust of the platform’s own operations, which no monoline lender can replicate.', code: { file: 'behavioural_pd.sql', lines: '<span class="c">-- PD from platform behaviour exogenous to any bureau (D1 + D3 exhaust)</span>\n<span class="k">SELECT</span> user_id,\n  <span class="nu">1.0</span> <span class="pu">/</span> (<span class="nu">1</span> <span class="pu">+</span> <span class="f">EXP</span>(<span class="pu">-</span>(\n    <span class="pu">-</span> <span class="nu">0.44</span> <span class="pu">*</span> d3_ontime_delivery_ratio_18m   <span class="c">-- courier reliability (D3)</span>\n    <span class="pu">-</span> <span class="nu">0.29</span> <span class="pu">*</span> d1_commute_regularity          <span class="c">-- mobility regularity (D1)</span>\n    <span class="pu">+</span> <span class="nu">0.61</span> <span class="pu">*</span> earnings_volatility\n    <span class="pu">-</span> <span class="nu">0.18</span> <span class="pu">*</span> tenure_months))) <span class="k">AS</span> pd_12m\n<span class="k">FROM</span> platform_behaviour;   <span class="c">-- no bureau feature required</span>' } },
          { id: 'pa2m2', title: 'Working-capital and instalment products that recycle into the flywheel', cite: 'S-406', body: 'The behavioural score powers three products — courier working-capital advances (D3), device instalments (D5), consumer BNPL on rides/charges (D1/D2). The chaining is the point: a device instalment puts a proprietary-sensor device (D5) into a customer’s hands, widening Breadth, so the credit product literally finances the moat’s data collection while earning a spread.' },
          { id: 'pa2m3', title: 'Portfolio risk and the loss-provisioning discipline', cite: 'S-407', body: 'Behavioural underwriting is powerful and pro-cyclical — the same D1/D3 signals that predict good times can turn together in a downturn — so Driver 2 hands a correlated-default risk to Driver 3. The provisioning discipline sizes for that correlation explicitly rather than averaging it away — the same honesty-about-the-tail a blended provision would hide.' },
        ] },
      { id: 'pa3', title: 'Driver 3 · Trust, fraud & compliance', cite: 'S-409',
        body: 'This is the term-owner mechanism for Trust: real-time fraud scoring on cross-domain signals, and a 14-country compliance perimeter that makes the trust legally durable.',
        mechanisms: [
          { id: 'pa3m1', title: 'Real-time fraud scoring on D6 signals fed by D1 and D5', cite: 'S-409', body: 'The engine scores every transaction in a ~40ms risk node, and its features are the third and fourth cross-domain couplings: fraud signals from D6, themselves assembled from D1 trajectory/location and D5 device fingerprints. A fraudster would have to fake a coherent physical-world footprint across mobility, devices, and payments simultaneously — a bar no monoline fraud system can set.' },
          { id: 'pa3m2', title: 'Compliance, licensing, and the 14-country perimeter', cite: 'S-410', body: 'Trust is also regulatory: Kepler holds or passports payment/e-money and lending licences across 14 countries and owns the reconciliation and reporting node. The perimeter is a moat in itself — the licences and cross-border reconciliation are expensive and slow to assemble, and they are the legal substrate that lets the trust term be monetised at all.' },
        ] },
      { id: 'pa4', title: 'Driver 4 · Monetization & interchange', cite: 'S-412',
        body: 'The domain turns a high moat into cash across four layers — but interchange, the obvious one, is legislated toward zero, so durable margin must come from the un-capped layers the flywheel enables.',
        table: { cols: ['Monetization layer', 'Regulatory exposure', 'Durability'], rows: [['Interchange', 'hard-capped / near-zero', 'low — legislated toward zero'], ['Take-rate (accepting merchants)', 'moderate', 'medium'], ['Float on balances', 'low', 'high — un-capped'], ['Credit spread + data products', 'own book', 'high — proprietary, un-capped']], note: 'Most gross profit now comes from the durable, un-capped layers; interchange is the floor, not the ramp (S-412/S-413).' },
        mechanisms: [
          { id: 'pa4m1', title: 'Interchange capture within regulated caps', cite: 'S-412', body: 'Interchange is asymmetrically capped across the footprint and legally near-zero across half of TPV, so the monetization model must respect it region-by-region and cannot lean on it. This is the structural fact — the same "the rate lever is already pulled" logic that forces the durable margin into the credit, float, and data layers.' },
          { id: 'pa4m2', title: 'Take-rate, float, and the blended monetization stack', cite: 'S-413', body: 'Kepler monetizes across four layers of different regulatory exposure; the durable margin lives in float and credit-plus-data, not interchange. The blended stack is what turns a high M into cash — and it is only high-margin because the credit and fraud layers underneath run on the other five domains’ data, which a monoline PSP does not have.' },
          { id: 'pa4m3', title: 'The ledger as monetization evidence', cite: 'S-416', body: 'Underneath the statement sits the raw ledger from Driver 1, read now as a monetization record: a single day’s mixed flows carry different margins, and the join — one user, many domains — is the proof that the durable margin comes from the cross-feeds, not the swipe. The swipe is what’s true; the trust is what counts.' },
        ] },
    ],
  },
  {
    id: 'devices', n: '05', name: 'Devices & Hardware', term: 'Data breadth (B)', today: '31% hardware GM, trails standalone', target: 'the breadth engine', swing: '',
    headline: 'We sell hardware to harvest data no one else has.',
    lede: 'On its own financials, Devices is the portfolio’s least impressive business — 31% hardware gross margin, real inventory and tariff risk, a supply chain with genuine concentration at Penang and Singapore, a ramp paced by the domains it depends on. Judged as a device company against a focused device company, it trails — exactly what the sum-of-parts frame predicts, and exactly the business an activist would tell Kepler to spin out. None of that should be argued away.',
    cite: 'S-501', finding: 'the hardware finances the sensor network',
    findingBody: 'Devices exists to widen Breadth (B) — proprietary sensor streams no competitor can buy. Every device is a carrier for the Kepler Sensor Module, and the hardware margin, thin on purpose, finances a five-modality sensing manifold (kinematic, environmental, positional, acoustic, RF) that no rival has jointly instrumented at fleet scale. That breadth is inert as hardware and decisive in D6’s models: kinematic road-roughness sharpens routing and siting, device fingerprints sharpen fraud. Run as a device company it trails; run as the breadth engine, its 31% margin is the price Kepler pays to own a data manifold that lifts four other domains at once.',
    drivers: [
      { id: 'de1', title: 'Driver 1 · The product line — four form factors, one manifold', cite: 'S-501',
        body: 'Four form factors wrap one shared sensor-and-compute core, and each device’s consumer value has to be real or the sensor never gets placed.',
        mechanisms: [
          { id: 'de1m1', title: 'The manifold-first design rule', cite: 'S-501', body: 'Every Kepler device is architected around the shared Kepler Sensor Module (KSM), with form-factor-specific carrier boards and enclosures wrapped around it. Design starts from the sensor manifold, not the product — so a phone, a beacon, an embedded node, and a wearable all sample the same modalities and speak the same data grammar into D6. The manifold, not the SKU, is the unit of strategy.' },
          { id: 'de1m2', title: 'The product mockup: what the Beacon actually shows', cite: 'S-502', body: 'The KB-1 Beacon’s value to the user must be genuinely useful — a real navigation-and-payments surface — or it never gets placed and the sensor never samples. The data-harvesting is invisible to the user by design; the interface earns its place on the desk, and the sensor rides along. A device that is only a sensor is a device that is thrown in a drawer.' },
        ] },
      { id: 'de2', title: 'Driver 2 · BOM, cost & margin', cite: 'S-504',
        body: 'The bill of materials is where the strategy becomes concrete — the sensors that widen Breadth are named line items, and the margin is thin on purpose because the return is data, not device profit.',
        table: { cols: ['KB-1 BOM (2m/yr run-rate)', 'Landed cost / unit', 'Role'], rows: [['SoC + compute', '$14.20', 'on-device inference'], ['Sensor manifold (IMU, env, RF, mic)', '$9.80', 'the actual product — Breadth (B)'], ['Display + enclosure', '$11.40', 'the consumer surface'], ['Radios + power + PCB', '$8.60', 'connectivity + placement'], ['Assembly + test + logistics', '$6.30', 'landed']], foot: ['Total landed BOM', '$50.30', '—'], note: 'The sensor manifold is ~$9.80 of the ~$50 BOM — the line that isn’t really a cost, it’s the acquisition price of a data stream (S-504/S-505).' },
        mechanisms: [
          { id: 'de2m1', title: 'The BOM cost table and the teardown that names the sensors', cite: 'S-504', body: 'The costed BOM at a 2m-unit run-rate names every sensor — IMU, environmental, RF, microphone — so the reader can see exactly which components manufacture Breadth. The teardown is the evidence surface: the sensor manifold is a modest fraction of BOM and the entire strategic point of the device, which is why the margin can be thin without the domain being a failure.' },
          { id: 'de2m2', title: 'The margin waterfall: ASP to gross margin, thin on purpose', cite: 'S-507', body: 'The waterfall from average selling price to a ~31% gross margin is deliberately thin: Devices prices to place sensors widely, not to maximise device profit. A focused device company would price for margin and ship fewer units; Kepler prices for coverage, because each placed device is a permanent node in the sensing manifold whose value is booked in D6, not here.', table: { cols: ['KB-1 margin waterfall', '$ / unit'], rows: [['ASP', '$72.90'], ['− landed BOM', '−$50.30'], ['− warranty + returns', '−$3.10'], ['− channel + fulfilment', '−$6.90']], foot: ['Gross margin (≈31%)', '$12.60'], negCols: [1], note: 'Thin on purpose: the return is a data node, priced for coverage not margin (S-507).' } },
        ] },
      { id: 'de3', title: 'Driver 3 · The supply chain — geography as sensor coverage', cite: 'S-509',
        body: 'The supply chain is a sensor-coverage decision as much as a cost one, and its concentration is a named risk the manufacturing plan has to manage.',
        mechanisms: [
          { id: 'de3m1', title: 'The supply-chain map: fabs, assembly, ports', cite: 'S-509', body: 'The physical flow from silicon to placement — fabs, assembly, ports — is mapped explicitly, because where devices are built and shipped determines where the sensor manifold can be densely placed. Geography is coverage: a supply constraint in one corridor is a Breadth gap in the cities that corridor serves.' },
          { id: 'de3m2', title: 'The manufacturing Gantt and the concentration risk it exposes', cite: 'S-511', body: 'The KB-1 v2 and embedded KN-2 ramp across FY26–FY27 is laid out on a Gantt that exposes genuine concentration at Penang and Singapore. The risk is named, not argued away — a single-site disruption stalls Breadth expansion, so the plan carries dual-sourcing and buffer as an explicit hedge rather than optimising purely for cost.' },
        ] },
      { id: 'de4', title: 'Driver 4 · Proprietary sensor data is the real product', cite: 'S-513',
        body: 'The manifold captures five modalities no competitor has jointly instrumented at fleet scale, and its payoff is realised entirely in D6’s models via specific, attributable cross-feeds.',
        mechanisms: [
          { id: 'de4m1', title: 'The five-modality manifold and its uniqueness', cite: 'S-513', body: 'The manifold captures five broad, mutually-reinforcing modalities — kinematic (400 Hz 6-axis IMU: road roughness, grip, crash signatures), environmental, positional, acoustic, and RF — that no rival has jointly instrumented at fleet scale. Uniqueness comes from the joint capture, not any single sensor: it is the combination across modalities and across 42 cities that is uncopyable.' },
          { id: 'de4m2', title: 'How breadth sharpens D6, and the value attribution', cite: 'S-514', body: 'The payoff is specific and attributable: kinematic road-roughness sharpens D1 routing and ride-comfort models and feeds D2 siting (rough corridors correlate with charger wear); device fingerprints sharpen D4 fraud. The value is booked where it lands — in four other domains’ models — which is why Devices’ own P&L understates it, and why the moat, not the SKU, is the correct denominator.' },
        ] },
    ],
  },
  {
    id: 'data', n: '06', name: 'Data & AI Platform', term: 'compounds all of M', today: '−$420m cost centre', target: 'the hub — built first', swing: '',
    headline: 'The moat is not a business — it is the hub of the flywheel.',
    lede: 'On today’s books, Domain 6 is a −$420m cost centre that owns no customer and sells no product, and the market’s ~35% conglomerate discount is a rational read of a sum-of-parts that genuinely does not clear. The platform is early: feature coverage is uneven across the 42 cities, the cross-join uplift is largest in three dense metros and thin elsewhere, and several return-edge models are still below the bar their data could support. Nothing here says the six businesses are individually excellent — they are not.',
    cite: 'S-601', finding: 'the −$420m is the price of the multiplier',
    findingBody: 'M is a product, and Domain 6 is the multiplication. It ingests all five domains into one grammar, holds Breadth as a shared feature store, and serves models back that make all five cheaper, safer, and stickier — producing more data, improving the models, closing the loop. The cross-join uplift (a Sankey’s +19%, an ablation’s +18.7 ROC points) grows every time a domain is sequenced on, so the moat widens with scale and sequencing beats focus. The −$420m is not a cost; it is the price of the multiplier, and cost per unit of M is falling as the same platform serves more domains. Cutting the hub is not a saving — it is choosing to be a conglomerate.',
    drivers: [
      { id: 'da1', title: 'Driver 1 · The platform architecture', cite: 'S-601',
        body: 'One ingestion spine, one feature store, one serving layer — the physical form of the flywheel: five streams in, models out, to the domains that fed them.',
        mechanisms: [
          { id: 'da1m1', title: 'A single ingestion spine that normalises six streams into one grammar', cite: 'S-601', body: 'Every interaction — a ride start, a charge session, a courier accept, a card authorisation, a device heartbeat — publishes to a single append-only event log in one grammar. Normalising six streams into one is the precondition for every cross-feed: without a shared grammar the domains hoard incompatible data and the terms only add.' },
          { id: 'da1m2', title: 'A feature store that is the physical form of Breadth (B)', cite: 'S-603', body: 'The feature store is where Breadth actually lives — mirrored offline (columnar, for training) and online (key-value, sub-10ms, for serving), point-in-time correct. Breadth is not an abstraction; it is a concrete, queryable surface, and its size is exactly the number of cross-domain features one user’s many streams can produce.' },
          { id: 'da1m3', title: 'A serving layer that returns models to the domains that fed them', cite: 'S-604', body: 'Breadth is inert until served back: one low-latency API with a shared contract lets any domain request a decision (route, site, match, authorise, flag) and receive it in milliseconds. The serving layer is the "out" arrow of the flywheel — the reason a domain’s data returns to it as a cheaper, better decision rather than sitting in a warehouse.' },
        ] },
      { id: 'da2', title: 'Driver 2 · The data flywheel', cite: 'S-605',
        body: 'Five domains’ data compounds into one moat through cross-domain joins that create features no single domain could hold — and the compounding shows up as the one economic number the document is anchored to.',
        mechanisms: [
          { id: 'da2m1', title: 'Cross-domain joins create features no single domain could hold', cite: 'S-605', body: 'The compounding is concrete: D1 location traces + D5 accelerometer telemetry + D3 courier GPS join on geohash × time to produce road_roughness and curb_availability features that improve D1 routing and D3 dispatch at once. A single-domain team cannot build these features because it does not hold the other domains’ streams — the join is the moat.' },
          { id: 'da2m2', title: 'The flywheel network graph: the coherency centrepiece', cite: 'S-606', body: 'The network graph is the single most important picture in the document: every feed is also a return, the loop that makes the wheel a wheel. Where a Sankey shows how much each domain feeds the moat, the graph shows the moat feeding each domain back — six nodes, every edge bidirectional, no domain a leaf.' },
          { id: 'da2m3', title: 'Compounding shows up as a rising blended contribution', cite: 'S-608', body: 'The flywheel’s output is economic: blended contribution/interaction from −$0.14 today to +$0.31 over ten years, attributed to the moat. Each 10% rise in served feature value lowers the marginal cost of a mobility decision, a logistics match, and a payment authorisation simultaneously — because all three read the same improved features. One investment in Breadth pays out across four domains at once, which is why the −$420m is the price of the multiplier.' },
        ] },
      { id: 'da3', title: 'Driver 3 · The models', cite: 'S-609',
        body: 'Compounded Breadth becomes decisions that move Density, Liquidity, and Trust — via a shared registry, a demonstrable breadth→performance link, and a pipeline any domain can extend but not fork.',
        mechanisms: [
          { id: 'da3m1', title: 'A shared model registry so one improvement propagates to five domains', cite: 'S-609', body: 'Models are not owned by domains; they are registered centrally with lineage and consumed via the serving API, so the routing, matching, and fraud models all draw from the same feature substrate. One improvement to a shared feature propagates to five domains at once — the organisational form of multiplication rather than addition.' },
          { id: 'da3m2', title: 'Model performance demonstrably tracks data breadth', cite: 'S-610', body: 'The claim that breadth causes performance is tested by ablation: train each model on a single-domain feature set, then on the full cross-joined set, and measure the lift — a demonstrable +18.7 ROC points on the fraud model. The ROC and confusion figures make the compounding empirical, not rhetorical: breadth is not asserted to help, it is shown to.' },
          { id: 'da3m3', title: 'A feature pipeline any domain can extend but not fork', cite: 'S-612', body: 'The pipeline is versioned, shared code: a domain adds a feature by contributing a transform that enforces point-in-time correctness, but cannot fork the pipeline into a private copy. Extend-but-not-fork is the governance that keeps the flywheel coherent — every domain’s contribution improves the shared substrate rather than fragmenting it back into six warehouses.' },
        ] },
      { id: 'da4', title: 'Driver 4 · The moat compounding — M made uncatchable', cite: 'S-614',
        body: 'The M identity is made real: each term is moved by a named mechanism, the moat widens with scale so sequencing beats focus, and the cost centre is the moat’s price, falling per unit of M.',
        mechanisms: [
          { id: 'da4m1', title: 'Each term of M is moved by a named mechanism, and D6 multiplies them', cite: 'S-614', body: 'M is a product and Domain 6 is the multiplication: Density (D1 fleet), Breadth (D5 manifold), Liquidity (D3 matcher), Trust (D2 uptime + D4 fraud) — each term is moved by a named, traceable mechanism, and D6 is what turns four separately-moved terms into one multiplied moat. The accounting is explicit, term by term, cross-feed by cross-feed.' },
          { id: 'da4m2', title: 'The moat widens with scale, so sequencing beats focus', cite: 'S-614', body: 'The cross-join uplift is a function of how many streams share a key, so it grows every time a domain is sequenced onto the platform. A focused specialist adding users gets more of one term; Kepler adding a domain gets more of the product — which is precisely why sequencing (build the hub, then wire domains onto it) beats focus (perfect one vertical).' },
          { id: 'da4m3', title: 'The cost centre is the moat’s price, falling per unit of M', cite: 'S-616', body: 'Domain 6 costs −$420m and produces no revenue of its own by construction — it sells nothing; it multiplies. The correct denominator is not revenue but M, and cost per unit of M is falling as the same platform serves more domains and more interactions. Judged as a P&L it is a loss; judged as the multiplier it is the cheapest asset in the company.' },
        ] },
    ],
  },
];

export const EVIDENCE: Record<string, { engine: string; text: string }> = {
  'S-001': { engine: 'S-0xx · thesis', text: 'Kepler is one flywheel, not six businesses. The moat is the shared data-and-network moat no single-vertical competitor can assemble; the six businesses are organs that feed it, and it lowers cost + raises trust back across all six. Break it up and you destroy the only defensible thing.' },
  'S-002': { engine: 'S-0xx · thesis', text: 'Moat M = D × B × L × T (a product, not a sum). Target: blended contribution/interaction −$0.14 → +$0.31 over ten years, driven by the moat lowering cost + raising trust across all six at once, not by any domain’s margin.' },
  'S-0sc': { engine: 'S-0xx · thesis', text: 'Scenarios (data-sharing regulation × cost of capital): Base ≈50% +$0.31, Bull ≈20% +$0.48, Bear ≈30% −$0.02; probability-weighted ≈ +$0.24. The fragile part is the flywheel’s legality, not its engineering.' },
  'S-seq': { engine: 'Synthesis', text: 'Sequencing is the strategy. Phase I: build D6 (the hub) FIRST, as infrastructure, even at −$420m/yr — the critical path. Build the hub before the spokes, or every domain hoards data that never compounds and the terms only add.' },
  'S-dep': { engine: 'Synthesis', text: 'The one dependency: the Data/AI platform (D6) must be built first and funded through its loss-making years before any cross-feed can flow. Cutting the −$420m hub is not a saving — it is choosing to be a conglomerate.' },
  'S-101': { engine: 'S-1xx · mobility', text: 'Mobility manufactures Interaction density (D), the feedstock the whole flywheel runs on. Utilization clears 70% in saturated zones; a ride is worth its fare plus the location/behaviour exhaust five domains consume.' },
  'S-104': { engine: 'S-1xx · mobility', text: 'Safety instrumented as an empirical frequency: miles-per-intervention improved 11.6× in a year; each intervention is a labelled example fed to D6.' },
  'S-110': { engine: 'S-1xx · mobility', text: 'The rider app’s strategic job is to keep density high — every point of retention/frequency adds interaction density to the feedstock the other five domains consume.' },
  'S-114': { engine: 'S-1xx · mobility', text: 'The sensor stack loses money per ride until solid-state lidar lands — a cost in mobility’s column, an asset in the moat’s (the cheapest way to instrument 42 cities continuously).' },
  'S-118': { engine: 'S-1xx · mobility', text: 'Energy sites chargers off D1’s proprietary dwell heatmaps — placed before demand exists, where the fleet shows the network will need them. Mobility data measurably lowers energy’s siting cost (D1→D2).' },
  'S-120': { engine: 'S-1xx · mobility', text: 'Payments’ best fraud signal is mobility’s trajectory-plus-fingerprint stream (D1→D4).' },
  'S-121': { engine: 'S-1xx · mobility', text: 'Raw sensor telemetry widens Breadth for Devices and every Data/AI model (D1→D5/D6); the fleet + device line share one sensor manifold.' },
  'S-201': { engine: 'S-2xx · energy', text: 'Energy sets a ~$0.082/kWh cost floor under D1/D3 that widens when the grid is expensive, and manufactures trust at the socket that Payments spends at the checkout. The charge is never the product.' },
  'S-203': { engine: 'S-2xx · energy', text: 'Vertical integration: because aggregate load is forecastable from fleet data, Kepler contracts power as an industrial buyer (PPAs, wholesale, storage), not a retail price-taker.' },
  'S-208': { engine: 'S-2xx · energy', text: 'The load curve has two dominant patterns; reading it (legible because the fleet’s own charging is a large predictable share) is the precondition for pricing + dispatch margin.' },
  'S-209': { engine: 'S-2xx · energy', text: 'One margin object prices demand to flatten peaks and dispatches charging/storage into troughs — cheaper because the fleet’s flexible load is a controllable input.' },
  'S-210': { engine: 'S-2xx · energy', text: '99.2% uptime; first-session success drives 4.1× retention. Trust in infrastructure is the frequency with which it works on arrival — reliability manufactures the Trust term.' },
  'S-211': { engine: 'S-2xx · energy', text: 'Trust earned at the socket is fungible: reliable-charger users convert to activated Kepler wallets at 58% vs a 29% baseline (D2→D4).' },
  'S-214': { engine: 'S-2xx · energy', text: 'A 10-year scenario tree (grid-price path → renewables mix → margin) yields a probability-weighted +$0.036/kWh — a utility-grade distribution, presented as a range.' },
  'S-215': { engine: 'S-2xx · energy', text: 'Data-led siting + dispatch bias Kepler toward the tree’s upper branches — the same D1-fed instruments that place the asset hedge the commodity risk.' },
  'S-301': { engine: 'S-3xx · logistics', text: 'Logistics owns Liquidity (L) — the probability a courier and order match inside the window both accept. A city can be illiquid with thousands on each side; a mismatched/mispriced/slow city clears at 61%. Liquidity is the product.' },
  'S-303': { engine: 'S-3xx · logistics', text: 'Two-sided funnel: L is two independent conversion pipelines (supply, demand); both leak at the same cliff. Managing one "orders" number hides which side is failing.' },
  'S-305': { engine: 'S-3xx · logistics', text: 'Cohort retention is the truth serum: the courier curve smiles (a professional core, 19% of couriers doing 68% of volume), the merchant curve flattens high. Liquidity is a retention problem, not acquisition.' },
  'S-308': { engine: 'S-3xx · logistics', text: 'A courier accepts/declines in <4s; guaranteed payout, honest ETA, surge, batching must be legible in that window or L fails one match at a time.' },
  'S-309': { engine: 'S-3xx · logistics', text: 'A professional core (19% of couriers, 68% of volume) is inelastic + cheap; the casual tail is elastic + expensive. Modelling marginal courier-hour cost by tier lets Kepler pay the core on Energy’s cost base.' },
  'S-312': { engine: 'S-3xx · logistics', text: 'Batch-optimal assignment (not greedy nearest): a bipartite match over each tick blended on ETA, batching gain, fairness, predicted acceptance (D6-served). Batching lets three drops share one trip.' },
  'S-313': { engine: 'S-3xx · logistics', text: 'The matcher is where the flywheel compounds fastest — every match/decline is a labelled example fed to D6; the 11-point fill-rate edge over a well-funded standalone at equal pay is this loop, not a subsidy.' },
  'S-316': { engine: 'S-3xx · logistics', text: 'Density is the batching multiplier: below a threshold each order consumes a whole trip; above it, three drops share one and effective supply triples with no extra courier. Kepler densifies into cells Mobility already mapped.' },
  'S-317': { engine: 'S-3xx · logistics', text: 'Surge is the equilibrium regulator: price pulls the elastic casual tail online (secondarily rations demand), holding L clearing — calibrated against the tiered marginal-cost model, not maximised.' },
  'S-401': { engine: 'S-4xx · payments', text: 'Payments moves Trust (T) as its primary lever and converts moat strength into cash. Fastest-growing (+58% yoy), contribution positive, most gross profit from durable un-capped layers.' },
  'S-402': { engine: 'S-4xx · payments', text: 'One double-entry ledger receives every domain’s postings against the same account graph — the raw material of cross-domain underwriting + monetization evidence.' },
  'S-403': { engine: 'S-4xx · payments', text: 'PSP orchestration across card schemes + local instant rails (UPI, PIX, PayNow) + RTP, routing each transaction to the cheapest compliant path — the cost + coverage lever that makes cash-free closure affordable.' },
  'S-404': { engine: 'S-4xx · payments', text: 'Cash-free closure of D1 + D3: removing cash friction raises completed-interaction count (Density) and clearing speed (Liquidity) — outcomes bought for the flywheel that never show on Payments’ P&L.' },
  'S-405': { engine: 'S-4xx · payments', text: 'Behavioural underwriting off D1/D3 exhaust: a D3 courier with 18 months on-time deliveries + stable D1 commuting is a better risk than a thin-file applicant with an identical bureau score. Proprietary + causal.' },
  'S-406': { engine: 'S-4xx · payments', text: 'The score powers courier working-capital (D3), device instalments (D5), consumer BNPL (D1/D2). A device instalment puts a proprietary-sensor device in hands — credit finances the moat’s data collection.' },
  'S-407': { engine: 'S-4xx · payments', text: 'Behavioural underwriting is pro-cyclical (D1/D3 signals turn together in a downturn); provisioning sizes for the correlated-default risk explicitly rather than averaging it.' },
  'S-409': { engine: 'S-4xx · payments', text: 'Real-time fraud scored in a ~40ms node on D6 signals built from D1 trajectory + D5 device fingerprints — a fraudster must fake a coherent physical footprint across three domains at once.' },
  'S-410': { engine: 'S-4xx · payments', text: '14-country payment/e-money + lending licences and cross-border reconciliation are a moat in themselves — the legal substrate that lets the Trust term be monetised.' },
  'S-412': { engine: 'S-4xx · payments', text: 'Interchange is asymmetrically capped and legally near-zero across half of TPV — the "payments company" framing is impossible; durable margin must come from un-capped float/credit/data layers.' },
  'S-413': { engine: 'S-4xx · payments', text: 'Four monetization layers of different regulatory exposure; the durable margin lives in float + credit-plus-data, high-margin only because the credit/fraud layers run on the other five domains’ data.' },
  'S-416': { engine: 'S-4xx · payments', text: 'The raw ledger read as a monetization record: a day’s mixed flows carry different margins, and the one-user-many-domains join proves the durable margin comes from the cross-feeds, not the swipe.' },
  'S-501': { engine: 'S-5xx · devices', text: 'Manifold-first design: every device wraps the shared Kepler Sensor Module; design starts from the sensor manifold, not the SKU, so all form factors speak one data grammar into D6.' },
  'S-502': { engine: 'S-5xx · devices', text: 'The KB-1 Beacon must be a genuinely useful navigation-and-payments surface or it never gets placed and the sensor never samples; the harvesting is invisible by design.' },
  'S-504': { engine: 'S-5xx · devices', text: 'KB-1 costed BOM (2m/yr run-rate): the sensor manifold (~$9.80 of a ~$50 landed BOM) is the line that isn’t a cost — it’s the acquisition price of a data stream.' },
  'S-507': { engine: 'S-5xx · devices', text: 'Margin waterfall ASP→GM lands at ~31%, thin on purpose: Devices prices to place sensors widely, not to maximise device profit — each placed device is a permanent node booked in D6.' },
  'S-509': { engine: 'S-5xx · devices', text: 'Supply-chain map (silicon → fabs → assembly → ports → placement): geography is coverage — a supply constraint is a Breadth gap in the cities that corridor serves.' },
  'S-511': { engine: 'S-5xx · devices', text: 'The KB-1 v2 + embedded KN-2 ramp (FY26–FY27 Gantt) exposes genuine concentration at Penang + Singapore; named + hedged with dual-sourcing + buffer.' },
  'S-513': { engine: 'S-5xx · devices', text: 'Five-modality manifold — kinematic (400Hz 6-axis IMU), environmental, positional, acoustic, RF — no rival has jointly instrumented at fleet scale. Uniqueness is the joint capture.' },
  'S-514': { engine: 'S-5xx · devices', text: 'Attributable cross-feeds: kinematic road-roughness sharpens D1 routing + comfort and feeds D2 siting; device fingerprints sharpen D4 fraud. Value booked in four domains’ models, not the SKU.' },
  'S-601': { engine: 'S-6xx · data/AI', text: 'One append-only event log normalises six streams into one grammar — the precondition for every cross-feed; without it the domains hoard incompatible data and terms only add.' },
  'S-603': { engine: 'S-6xx · data/AI', text: 'The feature store is the physical form of Breadth (B): mirrored offline (training) + online (sub-10ms serving), point-in-time correct.' },
  'S-604': { engine: 'S-6xx · data/AI', text: 'The serving layer returns models to the domains that fed them via one low-latency API — the "out" arrow of the flywheel that makes data return as a cheaper decision.' },
  'S-605': { engine: 'S-6xx · data/AI', text: 'Cross-domain joins: D1 location + D5 accelerometer + D3 courier GPS join on geohash×t → road_roughness + curb_availability features that improve D1 routing + D3 dispatch at once — a single domain cannot build these.' },
  'S-606': { engine: 'S-6xx · data/AI', text: 'The flywheel network graph is the coherency centrepiece: every feed is also a return, six nodes with no leaf — the loop that makes the wheel a wheel.' },
  'S-608': { engine: 'S-6xx · data/AI', text: 'Each 10% rise in served feature value lowers the marginal cost of a mobility decision, a logistics match, and a payment authorisation simultaneously — one investment in Breadth pays across four domains, so −$420m is the price of the multiplier. Contribution −$0.14→+$0.31.' },
  'S-609': { engine: 'S-6xx · data/AI', text: 'A shared model registry (with lineage) so one improvement to a shared feature propagates to five domains at once — multiplication, not addition, as an org structure.' },
  'S-610': { engine: 'S-6xx · data/AI', text: 'Breadth→performance tested by ablation: single-domain vs full cross-joined feature set → +18.7 ROC points on fraud. Compounding is empirical, not rhetorical.' },
  'S-612': { engine: 'S-6xx · data/AI', text: 'Extend-but-not-fork pipeline: a domain adds a feature by contributing a point-in-time-correct transform to the shared code, but cannot fork a private copy — the governance that keeps the flywheel coherent.' },
  'S-614': { engine: 'S-6xx · data/AI', text: 'Each M term is moved by a named mechanism and D6 multiplies them; cross-join uplift grows with every domain sequenced on (Sankey +19%, ROC +18.7pts) — so the moat widens with scale and sequencing beats focus.' },
  'S-616': { engine: 'S-6xx · data/AI', text: 'D6 costs −$420m and sells nothing by construction — it multiplies. The correct denominator is M, not revenue, and cost per unit of M is falling as the platform serves more domains.' },
};
